theme: jekyll-theme-dinky
title: Jacqueline Lee's Data Science Portfolio
logo: tcg_headshot.jpg
description: hello! here is a description.
navbar-links:
  About Me: "hello my name is jacqueline"
  Resources:
    - Bullet point 
    - bullet point
  Author's home: "https://deanattali.com"
