theme: jekyll-theme-minimal
title: Jacqueline Lee's Data Science Portfolio
logo: tcg_headshot.jpg
description: hello!
navbar-links:
  About Me: "hello"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
 
